import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import SidebarNav from "@/components/SidebarNav"
import TopBar from "@/components/TopBar"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Sidebar */}
        <SidebarNav />

        <main>
          <TopBar />

          <div className="flex gap-6 py-5 px-6 h-full">
            <div className="flex-1">
              <div className="bg-slate-300 h-full">{children}</div>
            </div>

            <div className="bg-white max-w-[416px] w-full sticky top-0 h-full">
              sidebar right
            </div>
          </div>
        </main>
      </body>
    </html>
  )
}
